# Generated by Django 6.0.5 on 2026-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutismSupportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('place_type', models.CharField(choices=[('government', 'حكومي'), ('private', 'خاص'), ('community', 'مجتمعي')], max_length=20)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
            ],
        ),
    ]
