# Generated by Django 6.0.5 on 2026-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autismsupportplace',
            name='city',
        ),
        migrations.AddField(
            model_name='autismsupportplace',
            name='region',
            field=models.CharField(choices=[('riyadh', 'منطقة الرياض'), ('eastern', 'المنطقة الشرقية'), ('makkah', 'منطقة مكة المكرمة'), ('madinah', 'منطقة المدينة المنورة'), ('asir', 'منطقة عسير'), ('jazan', 'جازان'), ('najran', 'نجران'), ('qassim', 'القصيم'), ('hail', 'حائل'), ('tabuk', 'تبوك'), ('jouf', 'الجوف'), ('northern_borders', 'الحدود الشمالية'), ('bahah', 'الباحة')], default='riyadh', max_length=50),
            preserve_default=False,
        ),
    ]
